### PR TITLE
ONA-897: Section: Try it -> Use real data for the section content

### PR DESCRIPTION
**Pull request by blattmann**
* Live data added

Ticket: https://stanwood.atlassian.net/browse/ONA-897

Hint: 
Run the project locally with `$ npm run serveme`
When the project is running please save once the file "styles.scss" to fire a css generation ;)

### CODE REVIEW

**Comment by hanneskl** [comment]
[Try_it.zip](https://github.com/stanwood/ON_AIR_Website/files/1590643/Try_it.zip)

**Comment by blattmann** [comment]
I cannot reproduce it.
There's no special rule for 27" displays.

Result from my device (same on iPhone7 plus and Galaxy s8+)

[try-it-2_720.zip](https://github.com/stanwood/ON_AIR_Website/files/1590692/try-it-2_720.zip)

**Comment by valeriopisapia** [comment]
Result on my MacBook Pro (Retina, 13-inch).
It seems working properly.

[valerio.m4v.zip](https://github.com/stanwood/ON_AIR_Website/files/1594726/valerio.m4v.zip)

**Comment by blattmann** [comment]
@hanneskl 
I was testing also on:

* 2012 iMac 27" (no Retina) 
* iPad Pro Retina
* iPhone 7 Plus
* Samsung Galaxy S6 Edge
* Samsung Galaxy S8+

and the result was fine.
What do we do?

**Pull request merged**
